name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        #default: 'dev'
        options:
          - 'dev'
          - 'test'
          - 'prod'

env:
  TF_WORKSPACE: ${{ github.event.inputs.environment }}

  
permissions:
    contents: "read"
    id-token: "write"
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: projects/596010007198/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: terraform-actions@terraform-actions.iam.gserviceaccount.com


      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"


      - name: Terraform init    
        run: terraform init

      - name: Terraform plan
        run: terraform plan
        working-directory: ../Terraform-Actions

      - name: Terraform apply
        run: terraform apply -auto-approve 
        working-directory: ../Terraform-Actions
         
        


