name: GitHub Actions with Workload Identity Federation Demo
on:
  push:
    branches:
      - dev
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: projects/596010007198/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: terraform-actions@terraform-actions.iam.gserviceaccount.com

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: Terraform init    
        run: terraform init

      - name: Terraform plan
        run: terraform plan
        working-directory: ../Terraform-Actions

      - name: Terraform apply
        run: terraform apply -auto-approve 
        working-directory: ../Terraform-Actions

#commment

